TEAM_NAME_RU = {
    "Argentina": "Аргентина",
    "Australia": "Австралия",
    "Austria": "Австрия",
    "Belgium": "Бельгия",
    "Bosnia & Herzegovina": "Босния и Герцеговина",
    "Brazil": "Бразилия",
    "Canada": "Канада",
    "Cape Verde": "Кабо-Верде",
    "Cape Verde Islands": "Кабо-Верде",
    "Colombia": "Колумбия",
    "Congo DR": "ДР Конго",
    "Costa Rica": "Коста-Рика",
    "Croatia": "Хорватия",
    "Curacao": "Кюрасао",
    "Curaçao": "Кюрасао",
    "Czech Republic": "Чехия",
    "Denmark": "Дания",
    "Ecuador": "Эквадор",
    "Egypt": "Египет",
    "England": "Англия",
    "France": "Франция",
    "Germany": "Германия",
    "Ghana": "Гана",
    "Haiti": "Гаити",
    "Iran": "Иран",
    "Iraq": "Ирак",
    "Italy": "Италия",
    "Ivory Coast": "Кот-д’Ивуар",
    "Japan": "Япония",
    "Jordan": "Иордания",
    "Mexico": "Мексика",
    "Morocco": "Марокко",
    "Netherlands": "Нидерланды",
    "New Zealand": "Новая Зеландия",
    "Norway": "Норвегия",
    "Panama": "Панама",
    "Paraguay": "Парагвай",
    "Poland": "Польша",
    "Portugal": "Португалия",
    "Qatar": "Катар",
    "Saudi Arabia": "Саудовская Аравия",
    "Scotland": "Шотландия",
    "Senegal": "Сенегал",
    "Serbia": "Сербия",
    "South Africa": "ЮАР",
    "South Korea": "Южная Корея",
    "Spain": "Испания",
    "Sweden": "Швеция",
    "Switzerland": "Швейцария",
    "Tunisia": "Тунис",
    "Turkey": "Турция",
    "Türkiye": "Турция",
    "Ukraine": "Украина",
    "Uruguay": "Уругвай",
    "USA": "США",
    "United States": "США",
    "Uzbekistan": "Узбекистан",
}


def get_team_name_ru(name: str | None) -> str:
    if not name:
        return ""

    return TEAM_NAME_RU.get(name, name)