"""Team-related constants used by the bot."""

TEAM_FLAGS = {
    # Русские названия
    "Мексика": "🇲🇽",
    "ЮАР": "🇿🇦",
    "Южная Корея": "🇰🇷",
    "Канада": "🇨🇦",
    "США": "🇺🇸",
    "Аргентина": "🇦🇷",
    "Бразилия": "🇧🇷",
    "Франция": "🇫🇷",
    "Испания": "🇪🇸",
    "Англия": "🏴",
    "Португалия": "🇵🇹",
    "Германия": "🇩🇪",
    "Нидерланды": "🇳🇱",
    "Бельгия": "🇧🇪",
    "Хорватия": "🇭🇷",
    "Италия": "🇮🇹",
    "Колумбия": "🇨🇴",
    "Сенегал": "🇸🇳",
    "Уругвай": "🇺🇾",
    "Япония": "🇯🇵",
    "Швейцария": "🇨🇭",
    "Дания": "🇩🇰",
    "Иран": "🇮🇷",
    "Турция": "🇹🇷",
    "Эквадор": "🇪🇨",
    "Австрия": "🇦🇹",
    "Нигерия": "🇳🇬",
    "Австралия": "🇦🇺",
    "Алжир": "🇩🇿",
    "Египет": "🇪🇬",
    "Норвегия": "🇳🇴",
    "Украина": "🇺🇦",
    "Панама": "🇵🇦",
    "Кот-д’Ивуар": "🇨🇮",
    "Польша": "🇵🇱",
    "Уэльс": "🏴",
    "Швеция": "🇸🇪",
    "Сербия": "🇷🇸",
    "Парагвай": "🇵🇾",
    "Чехия": "🇨🇿",
    "Венгрия": "🇭🇺",
    "Шотландия": "🏴",
    "Тунис": "🇹🇳",
    "Камерун": "🇨🇲",
    "ДР Конго": "🇨🇩",
    "Греция": "🇬🇷",
    "Словакия": "🇸🇰",
    "Венесуэла": "🇻🇪",
    "Узбекистан": "🇺🇿",
    "Коста-Рика": "🇨🇷",
    "Мали": "🇲🇱",
    "Перу": "🇵🇪",
    "Чили": "🇨🇱",
    "Катар": "🇶🇦",
    "Румыния": "🇷🇴",
    "Ирак": "🇮🇶",
    "Словения": "🇸🇮",
    "Ирландия": "🇮🇪",
    "Саудовская Аравия": "🇸🇦",
    "Новая Зеландия": "🇳🇿",
    "Босния и Герцеговина": "🇧🇦",

    # API/английские названия
    "Mexico": "🇲🇽",
    "South Africa": "🇿🇦",
    "South Korea": "🇰🇷",
    "Korea Republic": "🇰🇷",
    "Canada": "🇨🇦",
    "United States": "🇺🇸",
    "USA": "🇺🇸",
    "Argentina": "🇦🇷",
    "Brazil": "🇧🇷",
    "France": "🇫🇷",
    "Spain": "🇪🇸",
    "England": "🏴",
    "Portugal": "🇵🇹",
    "Germany": "🇩🇪",
    "Netherlands": "🇳🇱",
    "Belgium": "🇧🇪",
    "Croatia": "🇭🇷",
    "Italy": "🇮🇹",
    "Colombia": "🇨🇴",
    "Senegal": "🇸🇳",
    "Uruguay": "🇺🇾",
    "Japan": "🇯🇵",
    "Switzerland": "🇨🇭",
    "Denmark": "🇩🇰",
    "Iran": "🇮🇷",
    "IR Iran": "🇮🇷",
    "Turkey": "🇹🇷",
    "Türkiye": "🇹🇷",
    "Ecuador": "🇪🇨",
    "Austria": "🇦🇹",
    "Nigeria": "🇳🇬",
    "Australia": "🇦🇺",
    "Algeria": "🇩🇿",
    "Egypt": "🇪🇬",
    "Norway": "🇳🇴",
    "Ukraine": "🇺🇦",
    "Panama": "🇵🇦",
    "Côte d'Ivoire": "🇨🇮",
    "Ivory Coast": "🇨🇮",
    "Poland": "🇵🇱",
    "Wales": "🏴",
    "Sweden": "🇸🇪",
    "Serbia": "🇷🇸",
    "Paraguay": "🇵🇾",
    "Czechia": "🇨🇿",
    "Czech Republic": "🇨🇿",
    "Hungary": "🇭🇺",
    "Scotland": "🏴",
    "Tunisia": "🇹🇳",
    "Cameroon": "🇨🇲",
    "DR Congo": "🇨🇩",
    "Congo DR": "🇨🇩",
    "Greece": "🇬🇷",
    "Slovakia": "🇸🇰",
    "Venezuela": "🇻🇪",
    "Uzbekistan": "🇺🇿",
    "Costa Rica": "🇨🇷",
    "Mali": "🇲🇱",
    "Peru": "🇵🇪",
    "Chile": "🇨🇱",
    "Qatar": "🇶🇦",
    "Romania": "🇷🇴",
    "Iraq": "🇮🇶",
    "Slovenia": "🇸🇮",
    "Ireland": "🇮🇪",
    "Saudi Arabia": "🇸🇦",
    "New Zealand": "🇳🇿",
    "Bosnia and Herzegovina": "🇧🇦",
    "Bosnia & Herzegovina": "🇧🇦",

    # Заглушки
    "TBD": "🏳️",
}

TEAM_FLAG_CODES = {
    # Русские названия
    "Мексика": "mx",
    "ЮАР": "za",
    "Южная Корея": "kr",
    "Корея": "kr",
    "Канада": "ca",
    "США": "us",
    "Аргентина": "ar",
    "Бразилия": "br",
    "Франция": "fr",
    "Испания": "es",
    "Англия": "gb-eng",
    "Португалия": "pt",
    "Германия": "de",
    "Нидерланды": "nl",
    "Бельгия": "be",
    "Хорватия": "hr",
    "Италия": "it",
    "Колумбия": "co",
    "Сенегал": "sn",
    "Уругвай": "uy",
    "Япония": "jp",
    "Швейцария": "ch",
    "Дания": "dk",
    "Иран": "ir",
    "Турция": "tr",
    "Эквадор": "ec",
    "Австрия": "at",
    "Нигерия": "ng",
    "Австралия": "au",
    "Алжир": "dz",
    "Египет": "eg",
    "Норвегия": "no",
    "Украина": "ua",
    "Панама": "pa",
    "Кот-д’Ивуар": "ci",
    "Кот-д'Ивуар": "ci",
    "Польша": "pl",
    "Уэльс": "gb-wls",
    "Швеция": "se",
    "Сербия": "rs",
    "Парагвай": "py",
    "Чехия": "cz",
    "Венгрия": "hu",
    "Шотландия": "gb-sct",
    "Тунис": "tn",
    "Камерун": "cm",
    "ДР Конго": "cd",
    "Греция": "gr",
    "Словакия": "sk",
    "Венесуэла": "ve",
    "Узбекистан": "uz",
    "Коста-Рика": "cr",
    "Мали": "ml",
    "Перу": "pe",
    "Чили": "cl",
    "Катар": "qa",
    "Румыния": "ro",
    "Ирак": "iq",
    "Словения": "si",
    "Ирландия": "ie",
    "Саудовская Аравия": "sa",
    "Новая Зеландия": "nz",
    "Босния и Герцеговина": "ba",
    "Марокко": "ma",
    "Гаити": "ht",
    "Кюрасао": "cw",
    "Кюрасао": "cw",
    "Кабо-Верде": "cv",
    "Кабо Верде": "cv",
    "Гана": "gh",
    "Иордания": "jo",

    # API/английские названия
    "Mexico": "mx",
    "South Africa": "za",
    "South Korea": "kr",
    "Korea Republic": "kr",
    "Canada": "ca",
    "United States": "us",
    "USA": "us",
    "Argentina": "ar",
    "Brazil": "br",
    "France": "fr",
    "Spain": "es",
    "England": "gb-eng",
    "Portugal": "pt",
    "Germany": "de",
    "Netherlands": "nl",
    "Belgium": "be",
    "Croatia": "hr",
    "Italy": "it",
    "Colombia": "co",
    "Senegal": "sn",
    "Uruguay": "uy",
    "Japan": "jp",
    "Switzerland": "ch",
    "Denmark": "dk",
    "Iran": "ir",
    "IR Iran": "ir",
    "Turkey": "tr",
    "Türkiye": "tr",
    "Ecuador": "ec",
    "Austria": "at",
    "Nigeria": "ng",
    "Australia": "au",
    "Algeria": "dz",
    "Egypt": "eg",
    "Norway": "no",
    "Ukraine": "ua",
    "Panama": "pa",
    "Côte d'Ivoire": "ci",
    "Côte d’Ivoire": "ci",
    "Ivory Coast": "ci",
    "Poland": "pl",
    "Wales": "gb-wls",
    "Sweden": "se",
    "Serbia": "rs",
    "Paraguay": "py",
    "Czechia": "cz",
    "Czech Republic": "cz",
    "Hungary": "hu",
    "Scotland": "gb-sct",
    "Tunisia": "tn",
    "Cameroon": "cm",
    "DR Congo": "cd",
    "Congo DR": "cd",
    "Greece": "gr",
    "Slovakia": "sk",
    "Venezuela": "ve",
    "Uzbekistan": "uz",
    "Costa Rica": "cr",
    "Mali": "ml",
    "Peru": "pe",
    "Chile": "cl",
    "Qatar": "qa",
    "Romania": "ro",
    "Iraq": "iq",
    "Slovenia": "si",
    "Ireland": "ie",
    "Saudi Arabia": "sa",
    "New Zealand": "nz",
    "Bosnia and Herzegovina": "ba",
    "Bosnia & Herzegovina": "ba",
    "Morocco": "ma",
    "Haiti": "ht",
    "Curacao": "cw",
    "Curaçao": "cw",
    "Cape Verde": "cv",
    "Ghana": "gh",
    "Jordan": "jo",
}


# Short codes used by API-Football / imported fixtures. Keeping them separate
# prevents missing flags when a fixture stores the abbreviation instead of the
# full team name.
TEAM_FLAG_CODES.update({
    "MX": "mx", "MEX": "mx",
    "ZA": "za", "RSA": "za",
    "KR": "kr", "KOR": "kr",
    "CZ": "cz", "CZE": "cz",
    "CA": "ca", "CAN": "ca",
    "BA": "ba", "BIH": "ba",
    "QA": "qa", "QAT": "qa",
    "CH": "ch", "SUI": "ch",
    "US": "us", "USA": "us",
    "PY": "py", "PAR": "py",
    "AU": "au", "AUS": "au",
    "TR": "tr", "TUR": "tr",
    "BR": "br", "BRA": "br",
    "MA": "ma", "MAR": "ma",
    "HT": "ht", "HTI": "ht",
    "SCO": "gb-sct",
    "DE": "de", "DEU": "de", "GER": "de",
    "CW": "cw", "CUW": "cw",
    "CI": "ci", "CIV": "ci",
    "EC": "ec", "ECU": "ec",
    "NL": "nl", "NED": "nl",
    "JP": "jp", "JPN": "jp",
    "SE": "se", "SWE": "se",
    "TN": "tn", "TUN": "tn",
    "ES": "es", "ESP": "es",
    "CV": "cv", "CPV": "cv",
    "SA": "sa", "KSA": "sa",
    "UY": "uy", "URU": "uy",
    "BE": "be", "BEL": "be",
    "EG": "eg", "EGY": "eg",
    "IR": "ir", "IRN": "ir", "IRI": "ir",
    "NZ": "nz", "NZL": "nz",
    "FR": "fr", "FRA": "fr",
    "SN": "sn", "SEN": "sn",
    "IQ": "iq", "IRQ": "iq",
    "NO": "no", "NOR": "no",
    "AR": "ar", "ARG": "ar",
    "DZ": "dz", "DZA": "dz", "ALG": "dz",
    "AT": "at", "AUT": "at",
    "JO": "jo", "JOR": "jo",
    "PT": "pt", "POR": "pt",
    "CD": "cd", "COD": "cd",
    "UZ": "uz", "UZB": "uz",
    "CO": "co", "COL": "co",
    "ENG": "gb-eng",
    "HR": "hr", "CRO": "hr",
    "GH": "gh", "GHA": "gh",
    "PA": "pa", "PAN": "pa",
})

TEAM_FLAGS.update({
    "MX": "🇲🇽", "MEX": "🇲🇽",
    "ZA": "🇿🇦", "RSA": "🇿🇦",
    "KR": "🇰🇷", "KOR": "🇰🇷",
    "CZ": "🇨🇿", "CZE": "🇨🇿",
    "CA": "🇨🇦", "CAN": "🇨🇦",
    "BA": "🇧🇦", "BIH": "🇧🇦",
    "QA": "🇶🇦", "QAT": "🇶🇦",
    "CH": "🇨🇭", "SUI": "🇨🇭",
    "US": "🇺🇸",
    "PY": "🇵🇾", "PAR": "🇵🇾",
    "AU": "🇦🇺", "AUS": "🇦🇺",
    "TR": "🇹🇷", "TUR": "🇹🇷",
    "BR": "🇧🇷", "BRA": "🇧🇷",
    "MA": "🇲🇦", "MAR": "🇲🇦", "Morocco": "🇲🇦", "Марокко": "🇲🇦",
    "HT": "🇭🇹", "HTI": "🇭🇹", "Haiti": "🇭🇹", "Гаити": "🇭🇹",
    "SCO": "🏴", "Scotland": "🏴", "Шотландия": "🏴",
    "DE": "🇩🇪", "DEU": "🇩🇪", "GER": "🇩🇪",
    "CW": "🇨🇼", "CUW": "🇨🇼", "Curacao": "🇨🇼", "Curaçao": "🇨🇼", "Кюрасао": "🇨🇼",
    "CI": "🇨🇮", "CIV": "🇨🇮",
    "EC": "🇪🇨", "ECU": "🇪🇨",
    "NL": "🇳🇱", "NED": "🇳🇱",
    "JP": "🇯🇵", "JPN": "🇯🇵",
    "SE": "🇸🇪", "SWE": "🇸🇪",
    "TN": "🇹🇳", "TUN": "🇹🇳",
    "ES": "🇪🇸", "ESP": "🇪🇸",
    "CV": "🇨🇻", "CPV": "🇨🇻", "Cape Verde": "🇨🇻", "Кабо-Верде": "🇨🇻",
    "SA": "🇸🇦", "KSA": "🇸🇦",
    "UY": "🇺🇾", "URU": "🇺🇾",
    "BE": "🇧🇪", "BEL": "🇧🇪",
    "EG": "🇪🇬", "EGY": "🇪🇬",
    "IR": "🇮🇷", "IRN": "🇮🇷", "IRI": "🇮🇷",
    "NZ": "🇳🇿", "NZL": "🇳🇿",
    "FR": "🇫🇷", "FRA": "🇫🇷",
    "SN": "🇸🇳", "SEN": "🇸🇳",
    "IQ": "🇮🇶", "IRQ": "🇮🇶",
    "NO": "🇳🇴", "NOR": "🇳🇴",
    "AR": "🇦🇷", "ARG": "🇦🇷",
    "DZ": "🇩🇿", "DZA": "🇩🇿", "ALG": "🇩🇿",
    "AT": "🇦🇹", "AUT": "🇦🇹",
    "JO": "🇯🇴", "JOR": "🇯🇴", "Jordan": "🇯🇴", "Иордания": "🇯🇴",
    "PT": "🇵🇹", "POR": "🇵🇹",
    "CD": "🇨🇩", "COD": "🇨🇩",
    "UZ": "🇺🇿", "UZB": "🇺🇿",
    "CO": "🇨🇴", "COL": "🇨🇴",
    "ENG": "🏴",
    "HR": "🇭🇷", "CRO": "🇭🇷",
    "GH": "🇬🇭", "GHA": "🇬🇭", "Ghana": "🇬🇭", "Гана": "🇬🇭",
    "PA": "🇵🇦", "PAN": "🇵🇦",
})
